### ISSUE TITLE
Synchronize with v1.0.1

### ISSUE THREAD

**Issue by Kronuz** [bsdtrhodes/freebsd-fscd#2]
File used in the FreeBSD port (`fsc-1.0.1.tar.gz`) doesn't match with the content in this repository, it seems this repository is older... is it?

**Comment by bsdtrhodes** [comment]
Hi,

The repository is the latest version available.  I’ll need to look at
getting some time to update the port.  It rarely changes so you could just
pull from git.

—
Tom Rhodes

**Comment by Kronuz** [comment]
The thing is the code in the port is different from this one, apparently it has an extra option and something about a temporary file being created which this repository doesn’t have... plus a date in some file in the port tar.gz is newer than in here.

I also have quite a few changes I’ve made through the years to fsc, in my fork here at https://github.com/Kronuz/fsc ...maybe we could have those finally released as official in the next version. What do you think?

**Comment by Kronuz** [comment]
In the contrary, I believe I was comparing backwards... the new stuff seems from this repository. I’ll make a proper git fork and perhaps you could take some pull requests to get to publish all of my changes :)
